# Generated by Django 3.1.7 on 2023-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230524_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abc1',
            old_name='img2',
            new_name='imgp',
        ),
        migrations.RenameField(
            model_name='abc2',
            old_name='img3',
            new_name='imgpr',
        ),
        migrations.RenameField(
            model_name='abc3',
            old_name='img4',
            new_name='imgw',
        ),
    ]
