# Generated by Django 3.1.7 on 2023-05-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230530_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abc',
            old_name='img',
            new_name='imgf',
        ),
    ]
